namespace Sudoku.Shared.Network
{
    public enum MessageType
    {
        Handshake,
        HandshakeAccepted,
        Heartbeat,
        HeartbeatAck,
        Error,
        Reconnect,
        ReconnectAccepted,
        PlayerDisconnected,
        ListRooms,
        CreateRoom,
        JoinRoom,
        LeaveRoom,
        RoomUpdated,
        StartMatch,
        MatchPrepared,
        PlayerReady,
        MatchStarted,
        GetMatchStatus,
        MatchStatusUpdated,
        SubmitMove,
        MoveResult,
        OpponentProgressUpdated,
        MatchFinished
    }
}
